### ISSUE TITLE
Receiving Error when adding files

### ISSUE THREAD

**Issue by PaulJManoogian** [Digiography/blender_addon_pbr#8] opened 2019-07-15 16:31 UTC
Hi,
Here's the error I get in the script window:

```
Traceback (most recent call last):
  File "C:\Users\paulj\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender_addon_pbr-master\dks_pbr.py", line 617, in execute
    _nodes['dks_pbr_texture_'+self.node_name].image=bpy.data.images.load(_filepath)
KeyError: 'bpy_prop_collection[key]: key "dks_pbr_texture_normal" not found'

location: <unknown location>:-1

```
Can you tell me what I might have set up incorrectly?  The file is saved before I add the normal, in this case.

**Comment by DigiKrafting** [comment] 2019-07-15 17:49
I was unable to reproduce the error. I was able to replace the normal map without error. I also created the nodes via my Substance Painter addon and was able to replace the normal map via this addon. This error would only occur if the image texture node for the normal map was created manually and not by the addon, as an ID, in this case "dks_pbr_texture_normal" is assigned to the image texture node. If you're using with my Substance Painter addon, be sure to have the lastest versions of both addons installed as they are designed to work with each other and share the same ID's. I did however find a bug, when replacing the normal map texture image, the color space reverts to the default "SRGB". I'll upload a fix for that now. Please let me know if your using the latest versions of my addons and if you are, the steps i can take to reproduce the error.

**Comment by DigiKrafting** [comment] 2019-07-15 17:54
It just occurred to me, did you create the nodes first via "Create - Auto Detect" or "Create Metallic Roughness" buttons? "Create - Auto Detect" requires the "Auto Textures Path" but if you click on the "Create Metallic Roughness" button, the nodes are created and images can be assigned. I'll update the addon to hide the assign/replace textire file buttons until the nodes are created to avoid confusion in using the addon.

**Comment by DigiKrafting** [comment] 2019-07-15 18:21
I've uploaded a fix for the color space issue, the texture files are now hidden until the nodes are created and I've added a usage section to the readme to make this clear. Please let me know if this fixes the issue you had, thanks.

**Closed as completed** 2019-07-18 15:43 UTC
